config/routes.rb
Fmtss::Application.routes.draw do
  resources :parts

  root :to => 'parts#index'

end

app/models/part.rb
class Part < ActiveRecord::Base
  attr_accessible :description, :item, :oem_part_number, :part_number, :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parts }
    end
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/new
  # GET /parts/new.json
  def new
    @part = Part.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/1/edit
  def edit
    @part = Part.find(params[:id])
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(params[:part])

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parts/1
  # PUT /parts/1.json
  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Florida Machine Tools Supplies &amp; Services</title>
        <%= stylesheet_link_tag "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/parts/_form.html.erb
<%= form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br />
    <%= f.number_field :item %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "30x4" %>
  </div>
  <div class="field">
    <%= f.label :part_number %><br />
    <%= f.text_field :part_number %>
  </div>
  <div class="field">
    <%= f.label :oem_part_number %><br />
    <%= f.text_area :oem_part_number, :size => "30*4" %>
  </div>
  <div class="actions">
    <%= f.submit "Add New Part" %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<h1>Florida Machine Tools Supplies &amp; Services</h1>

<table class="table table-striped">
  <tr>
    <th>Item</th>
    <th>Quantity</th>
    <th>Description</th>
    <th>Part Number</th>
    <th>OEM Part Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parts.each do |part| %>
  <tr>
    <td><%= part.item %></td>
    <td><%= part.quantity %></td>
    <td><%= part.description %></td>
    <td><%= part.part_number %></td>
    <td><%= part.oem_part_number %></td>
    <td><%= link_to 'Show', part %></td>
    <td><%= link_to 'Edit', edit_part_path(part) %></td>
    <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add New Part', new_part_path, :class => 'btn btn-success' %>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @part.item %>
</p>

<p>
  <b>Quantity:</b>
  <%= @part.quantity %>
</p>

<p>
  <b>Description:</b>
  <%= @part.description %>
</p>

<p>
  <b>Part number:</b>
  <%= @part.part_number %>
</p>

<p>
  <b>Oem part number:</b>
  <%= @part.oem_part_number %>
</p>


<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>